{
  try {
    command.execute();
  }
 catch (  Throwable e) {
    Assert.assertThat(t.getName(),is(e.getClass().getName()));
    return;
  }
  throw new AssertionError("Expected exception wasn't thrown: " + t.getName());
}
